# Generated by Django 4.1.3 on 2022-11-25 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='videos',
            fields=[
                ('id', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('title', models.TextField()),
                ('description', models.TextField()),
                ('publish_date_time', models.DateTimeField()),
                ('thumbnail_url', models.URLField(blank=True, max_length=1000, null=True)),
            ],
        ),
    ]
